# Generated by Django 4.2.7 on 2024-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_UniquePublicId"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, choices=[("admin", "Admin"), ("manager", "Manager"), ("developer", "Developer")], max_length=32),
        ),
    ]
