# Generated by Django 4.2.7 on 2024-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
